services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    env_file:
      - ./packages/frontend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    env_file:
      - ./packages/backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@database:5432/robiumdb
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - robium-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=robiumdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ros-container:
    build:
      context: ./ros
      dockerfile: Dockerfile
    # Add other ROS-specific configurations here
    # (e.g., volumes, environment variables, command)
    # This service is a placeholder for now.

volumes:
  robium-db-data:
